### ISSUE TITLE
TypeError: set_columns() got an unexpected keyword argument 'parents'

### ISSUE THREAD

**Issue by xin-huang** [popsim-consortium/analysis2#16]
Hi,

I tried to run these codes from https://stdpopsim.readthedocs.io/en/latest/tutorial.html#incorporating-selection

```
import numpy as np
import stdpopsim


def KimDFE():
    """
    Return neutral and negative MutationType()s representing a human DFE.
    Kim et al. (2018), p.23, http://doi.org/10.1371/journal.pgen.1007741
    """
    neutral = stdpopsim.ext.MutationType()
    gamma_shape = 0.186  # shape
    gamma_mean = -0.01314833  # expected value
    h = 0.5  # dominance coefficient
    negative = stdpopsim.ext.MutationType(
        dominance_coeff=h,
        distribution_type="g",  # gamma distribution
        distribution_args=[gamma_mean, gamma_shape],
    )
    # neutral mutations have 0 proportion because they are not simulated by SLiM
    return {"mutation_types": [neutral, negative], "proportions": [0.0, 0.7]}


species = stdpopsim.get_species("HomSap")
model = species.get_demographic_model("OutOfAfrica_3G09")
contig = species.get_contig("chr1", length_multiplier=0.001)
contig.clear_genomic_mutation_types()
samples = model.get_samples(100, 100, 100)  # YRI, CEU, CHB

# neutral and deleterious mutations occur across the whole contig
contig.add_genomic_element_type(
    intervals=np.array([[0, int(contig.recombination_map.sequence_length)]]),
    **KimDFE(),
)

engine = stdpopsim.get_engine("slim")
ts = engine.simulate(
    model,
    contig,
    samples,
    seed=123,
    slim_scaling_factor=10,
    slim_burn_in=10,
)

mut_info = {}
for mut in ts.mutations():
    for j, md in zip(mut.derived_state.split(","), mut.metadata["mutation_list"]):
        if j not in mut_info:
            mut_info[int(j)] = md

num_neutral = sum([mut_info[j]["selection_coeff"] == 0.0 for j in mut_info])
print(
    f"There are {num_neutral} neutral mutations, and "
    f"{len(mut_info) - num_neutral} nonneutral mutations."
)
```

But I got the following error

```
Traceback (most recent call last):
  File "test2.py", line 36, in <module>
    ts = engine.simulate(
  File "/xdisk/rgutenk/xinhuang/software/anaconda3/lib/python3.8/site-packages/stdpopsim-0.1.3.dev452+gd5aa3f3-py3.8.egg/stdpopsim/slim_engine.py", line 1194, in simulate
    ts = self._recap_and_rescale(
  File "/xdisk/rgutenk/xinhuang/software/anaconda3/lib/python3.8/site-packages/stdpopsim-0.1.3.dev452+gd5aa3f3-py3.8.egg/stdpopsim/slim_engine.py", line 1303, in _recap_and_rescale
    ts = msprime.sim_ancestry(
  File "/xdisk/rgutenk/xinhuang/software/anaconda3/lib/python3.8/site-packages/msprime/ancestry.py", line 1161, in sim_ancestry
    return _wrap_replicates(
  File "/xdisk/rgutenk/xinhuang/software/anaconda3/lib/python3.8/site-packages/msprime/ancestry.py", line 668, in _wrap_replicates
    deque = collections.deque(iterator, maxlen=1)
  File "/xdisk/rgutenk/xinhuang/software/anaconda3/lib/python3.8/site-packages/msprime/ancestry.py", line 1448, in run_replicates
    tables = tskit.TableCollection.fromdict(self.tables.asdict())
  File "/xdisk/rgutenk/xinhuang/software/anaconda3/lib/python3.8/site-packages/tskit/tables.py", line 2190, in fromdict
    tables.individuals.set_columns(**tables_dict["individuals"])
TypeError: set_columns() got an unexpected keyword argument 'parents'
```

The packages I used are

```
stdpopsim==0.1.3.dev452+gd5aa3f3
msprime==1.0.2
tskit==0.3.5
```

Could you please help me fix this issue? Thank you.

**Comment by jeromekelleher** [comment]
I think you need a more recent version of tskit for working with msprime >= 1. Try ``pip install tskit --upgrade``

**Comment by xin-huang** [comment]
Thank you Jerome, it works.
